server:
  port: 8085

spring:
  data:
    mongodb:
      uri: mongodb+srv://harishpugal06:1234@cluster0.vye37.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: orderservice
  application:
    name: orderservice

eureka:
  client:
    service-url:
      defaultZone: http://@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# Configuration for the Notification Service
notification-service:
  base-url: http://localhost:8083

# Configuration for the User Service
user-service:
  base-url: http://localhost:8086

# Kafka configuration (if required for event publishing)
kafka:
  bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
