spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: userservice

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://@localhost:8761/eureka/ # Discovery Service URL with credentials
    register-with-eureka: true
    fetch-registry: true